%% ELECTROENCEPHALOGRAPHY PREPROCESSING
% -------------------------------------------------------------------------
% Chema Peñalver
% AttExpLoc_EEG
% cgpenalver@ugr.es
% CIMCYC - University of Granada
% -------------------------------------------------------------------------

clear
run conf
run subjects_to_compute

%% Directories:
dir_to_load = '../../../Data/EEG/trialrejected/';
dir_to_save = '../../../Data/EEG/precond/';
create_folder(dir_to_save);

% Automatic EEG preprocessing after ICA and trial prunning:
%
% - 1. Interpolation
% - 2. Add reference electrode
% - 3. Re-reference

for sub = 1: length(subjects_to_load)
    % PRINT FILENAME:
    disp(['<strong>SUBJECT:' subjects_to_load_trialpruned{sub} '</strong>']);

    % LOAD SUBJECT
    EEG = pop_loadset('filename',subjects_to_load_trialpruned{sub},'filepath',dir_to_load);

    % Electrode interpolation
        if ~isempty(channels_to_throw{sub})
            EEG = pop_interp(EEG,channels_to_throw{sub},'spherical');
        end
    % Add reference electrode manually:
        EEG = pop_chanedit(EEG, 'append',63,...
            'changefield',{64 'labels' 'FCz'},...
            'changefield',{64 'Y' '0'},...
            'changefield',{64 'Z' '67.5'},...
            'changefield',{64 'Z' ''},...
            'changefield',{64 'Y' ''},...
            'changefield',{64 'sph_theta' '0'},...
            'changefield',{64 'sph_phi' '67.5'},...
            'changefield',{64 'sph_radius' '1'},...
            'changefield',{64 'type' 'REF'});
    % Data re-reference
        EEG = pop_reref( EEG, [],'refloc',struct('labels',{'FCz'},...
            'sph_radius',{1},...
            'sph_theta',{0},...
            'sph_phi',{67.5},...
            'theta',{0},...   
            'radius',{0.125},...
            'X',{0.38268},...
            'Y',{0},...
            'Z',{0.92388},...
            'type',{'REF'},...
            'ref',{''},...
            'urchan',{[]},'datachan',{0},...
            'sph_theta_besa',{22.5},'sph_phi_besa',{90}));
    %% Save 
    EEG.setname = [subjects_to_load{sub}(1:4) '_precond'];
    
    EEG = pop_saveset(EEG, 'filename',EEG.setname,'filepath', dir_to_save);

    
end
    